--REQUEST TYPE LOOKUP TABLE
CREATE TABLE RQ_TYPE (
RQ_TYPE_ID INT,
RQ_TYPE VARCHAR2(4000),

PRIMARY KEY (RQ_TYPE_ID)
);

-- RQ STATUS LOOKUP TABLE
CREATE TABLE RQ_STATUS (
RQ_STATUS_ID INT,
RQ_STATUS VARCHAR2(4000),

PRIMARY KEY (RQ_STATUS_ID)
);

--POSITION LOOKUP TABLE
CREATE TABLE POSITION (
Pos_ID INT,
POS_Type VARCHAR2(4000),

PRIMARY KEY (Pos_ID)
);

--USER TABLE
CREATE TABLE USERS (
U_ID INT,
FNAME VARCHAR2(4000),
LNAME VARCHAR2(4000),
EMAIL VARCHAR2(4000),
password VARCHAR2(4000),
Pos_ID INT,

PRIMARY KEY(u_id),
FOREIGN KEY (Pos_ID)REFERENCES POSITION (Pos_ID) 
);

--REIMBURSEMENT TABLE
CREATE TABLE REIMBURSEMENT(
R_ID INT,
Emp_U_ID INT,
Mgr_U_ID INT,
AMT INT,
DESCRIPTION VARCHAR2(4000),
IMG BLOB,
TIMESUBMISSION TIMESTAMP,
RQ_TYPE INT,
RQ_STATUS_ID,

PRIMARY KEY (R_ID),
FOREIGN KEY (Emp_U_ID) REFERENCES USERS (U_ID),
FOREIGN KEY (Mgr_U_ID) REFERENCES USERS (U_ID),
FOREIGN KEY (RQ_TYPE_ID)REFERENCES RQ_TYPE (RQ_TYPE_ID),
FOREIGN KEY (RQ_STATUS_ID)REFERENCES RQ_STATUS (RQ_STATUS_ID)
);

