--------------------------------------------------------
--  File created - Tuesday-August-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type EMP_TABLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "CHINOOK"."EMP_TABLE" AS TABLE OF employee;

/
--------------------------------------------------------
--  DDL for Table ALBUM
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."ALBUM" 
   (	"ALBUMID" NUMBER, 
	"TITLE" VARCHAR2(160 BYTE), 
	"ARTISTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARTIST
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."ARTIST" 
   (	"ARTISTID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."CUSTOMER" 
   (	"CUSTOMERID" NUMBER, 
	"FIRSTNAME" VARCHAR2(40 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"COMPANY" VARCHAR2(80 BYTE), 
	"ADDRESS" VARCHAR2(70 BYTE), 
	"CITY" VARCHAR2(40 BYTE), 
	"STATE" VARCHAR2(40 BYTE), 
	"COUNTRY" VARCHAR2(40 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(24 BYTE), 
	"FAX" VARCHAR2(24 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"SUPPORTREPID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."EMPLOYEE" 
   (	"EMPLOYEEID" NUMBER, 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"REPORTSTO" NUMBER, 
	"BIRTHDATE" DATE, 
	"HIREDATE" DATE, 
	"ADDRESS" VARCHAR2(70 BYTE), 
	"CITY" VARCHAR2(40 BYTE), 
	"STATE" VARCHAR2(40 BYTE), 
	"COUNTRY" VARCHAR2(40 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(24 BYTE), 
	"FAX" VARCHAR2(24 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GENRE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."GENRE" 
   (	"GENREID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."INVOICE" 
   (	"INVOICEID" NUMBER, 
	"CUSTOMERID" NUMBER, 
	"INVOICEDATE" DATE, 
	"BILLINGADDRESS" VARCHAR2(70 BYTE), 
	"BILLINGCITY" VARCHAR2(40 BYTE), 
	"BILLINGSTATE" VARCHAR2(40 BYTE), 
	"BILLINGCOUNTRY" VARCHAR2(40 BYTE), 
	"BILLINGPOSTALCODE" VARCHAR2(10 BYTE), 
	"TOTAL" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICELINE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."INVOICELINE" 
   (	"INVOICELINEID" NUMBER, 
	"INVOICEID" NUMBER, 
	"TRACKID" NUMBER, 
	"UNITPRICE" NUMBER(10,2), 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDIATYPE
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."MEDIATYPE" 
   (	"MEDIATYPEID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYLIST
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."PLAYLIST" 
   (	"PLAYLISTID" NUMBER, 
	"NAME" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYLISTTRACK
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."PLAYLISTTRACK" 
   (	"PLAYLISTID" NUMBER, 
	"TRACKID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRACK
--------------------------------------------------------

  CREATE TABLE "CHINOOK"."TRACK" 
   (	"TRACKID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"ALBUMID" NUMBER, 
	"MEDIATYPEID" NUMBER, 
	"GENREID" NUMBER, 
	"COMPOSER" VARCHAR2(220 BYTE), 
	"MILLISECONDS" NUMBER, 
	"BYTES" NUMBER, 
	"UNITPRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INVOICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_INVOICE" ON "CHINOOK"."INVOICE" ("INVOICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ALBUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_ALBUM" ON "CHINOOK"."ALBUM" ("ALBUMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ARTIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_ARTIST" ON "CHINOOK"."ARTIST" ("ARTISTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEDIATYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_MEDIATYPE" ON "CHINOOK"."MEDIATYPE" ("MEDIATYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PLAYLISTTRACK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_PLAYLISTTRACK" ON "CHINOOK"."PLAYLISTTRACK" ("PLAYLISTID", "TRACKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CUSTOMER
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_CUSTOMER" ON "CHINOOK"."CUSTOMER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INVOICELINE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_INVOICELINE" ON "CHINOOK"."INVOICELINE" ("INVOICELINEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYEE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_EMPLOYEE" ON "CHINOOK"."EMPLOYEE" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRACK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_TRACK" ON "CHINOOK"."TRACK" ("TRACKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_GENRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_GENRE" ON "CHINOOK"."GENRE" ("GENREID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PLAYLIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "CHINOOK"."PK_PLAYLIST" ON "CHINOOK"."PLAYLIST" ("PLAYLISTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AFTERDELETE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHINOOK"."AFTERDELETE" 
AFTER DELETE ON customer
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Good job for deleting!');
END;
/
ALTER TRIGGER "CHINOOK"."AFTERDELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AFTERINSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHINOOK"."AFTERINSERT" 
AFTER INSERT ON employee
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Good job for inserting!');
END;
/
ALTER TRIGGER "CHINOOK"."AFTERINSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AFTERUPDATE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHINOOK"."AFTERUPDATE" 
AFTER UPDATE ON album
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Good job for updating!');
END;
/
ALTER TRIGGER "CHINOOK"."AFTERUPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Procedure DELETEINVOICE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."DELETEINVOICE" (invoid INT)
AS
BEGIN
    DELETE FROM invoiceline
    WHERE invoiceline.invoiceid = invoid; 
    DELETE FROM invoice
    WHERE invoice.invoiceid = invoid;
END;

/
--------------------------------------------------------
--  DDL for Procedure FIRSTANDLASTNAME
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."FIRSTANDLASTNAME" 
AS
BEGIN
--      SET NOCOUNT ON;
      SELECT firstname + ' ' + lastname AS fullname
      FROM employee;
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_ALL_NAMES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."GET_ALL_NAMES" (cursorParam OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN cursorParam FOR
  SELECT firstname, lastname FROM employee;
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_MANAGER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."GET_MANAGER" (eid INT, emp OUT VARCHAR2)
AS 
BEGIN
    SELECT firstname
    INTO emp
    FROM employee
    WHERE reportsto = eid;
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_NAME_COMPANY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."GET_NAME_COMPANY" (cid IN NUMBER, emp OUT VARCHAR2)
AS
BEGIN
SELECT firstname INTO emp FROM customer WHERE customerid = cid;
SELECT company INTO emp FROM customer WHERE customerid = cid;
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_CUSTOMER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."INSERT_CUSTOMER" (numId IN INT, fname IN VARCHAR2, lname IN VARCHAR2, mail IN VARCHAR2)
IS
BEGIN
    INSERT INTO customer(customerid, firstname, lastname, email) VALUES (numId, fname, lname, mail);
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEINFO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CHINOOK"."UPDATEINFO" (lname VARCHAR2, fname VARCHAR2, address VARCHAR2, city VARCHAR2, s VARCHAR2, 
                                        country VARCHAR2, zip VARCHAR2, phoneNum VARCHAR2, faxNum VARCHAR2, mail VARCHAR2, eid INT)
AS
BEGIN 
    UPDATE employee e SET e.lastname = lname, e.firstname = fname, e.address = address, e.city = city, e.state = s,
    e.country = country, e.postalcode = zip, e.phone = phoneNum, e.fax = faxNum, e.email = mail
    WHERE e.employeeId = eid;
END;

/
--------------------------------------------------------
--  DDL for Function AVERAGEPRICE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."AVERAGEPRICE" 
RETURN NUMBER
    IS price NUMBER;
BEGIN
    SELECT AVG(unitprice)
    INTO price
    FROM invoiceline;
    RETURN price;
END;

/
--------------------------------------------------------
--  DDL for Function BORNAFTER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."BORNAFTER" (@birthdate DATE)
RETURNS table
    IS
RETURN
    SELECT * FROM EMPLOYEE WHERE birthdate > @birthdate;

    SELECT * FROM bornAfter('01-Jan-69');

/
--------------------------------------------------------
--  DDL for Function BORN_AFTER_1968
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."BORN_AFTER_1968" 
RETURN SYS_REFCURSOR
    IS emp_born_after SYS_REFCURSOR;
BEGIN
    OPEN emp_born_after FOR
    SELECT *
    FROM employee
    WHERE birthdate > '01-jan-69';
    RETURN emp_born_after;
END;

/
--------------------------------------------------------
--  DDL for Function FINDEXPENSIVE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."FINDEXPENSIVE" 
RETURN SYS_REFCURSOR
    IS expense SYS_REFCURSOR;
BEGIN
OPEN expense FOR
SELECT unitprice 
FROM track
WHERE unitprice = ( 
    SELECT MAX(unitprice)
    FROM track
    );
RETURN expense;
END;

/
--------------------------------------------------------
--  DDL for Function GETAVERAGE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."GETAVERAGE" 
RETURN INT
    IS average INT;
BEGIN
    SELECT AVG(total)
    INTO average
    FROM invoice;
    RETURN average;
END;

/
--------------------------------------------------------
--  DDL for Function GETDATE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."GETDATE" 
RETURN VARCHAR2 
    IS currDate VARCHAR2(4000);
BEGIN
    SELECT TO_CHAR(sysdate,'MM-DD-YY HH12:MI:SS')
    INTO currDate
    FROM dual;
    RETURN (currDate);
END;

/
--------------------------------------------------------
--  DDL for Function GETLENGTH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."GETLENGTH" (mediaid INT)
RETURN INT
    IS l INT;
BEGIN
    SELECT LENGTH(name)
    INTO l
    FROM mediatype
    WHERE mediatypeid = mediaid;
    RETURN (l);
END;

/
--------------------------------------------------------
--  DDL for Function GET_AVERAGE_PRICE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."GET_AVERAGE_PRICE" 
RETURN NUMBER
IS
    average_price NUMBER;
BEGIN
    SELECT AVG(unitprice) INTO average_price FROM invoiceline;
    RETURN average_price;
END;

/
--------------------------------------------------------
--  DDL for Function GET_MOST_EXPENSIVE_TRACK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "CHINOOK"."GET_MOST_EXPENSIVE_TRACK" 
RETURN SYS_REFCURSOR
    AS curso SYS_REFCURSOR;
BEGIN
    OPEN curso
        FOR SELECT *
        FROM track
        WHERE unitprice = (SELECT MAX(unitprice) FROM track);
    RETURN curso;
END;

/
--------------------------------------------------------
--  Constraints for Table GENRE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY ("GENREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."GENRE" MODIFY ("GENREID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALBUM
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."ALBUM" ADD CONSTRAINT "PK_ALBUM" PRIMARY KEY ("ALBUMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."ALBUM" MODIFY ("ARTISTID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."ALBUM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."ALBUM" MODIFY ("ALBUMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."EMPLOYEE" ADD CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."EMPLOYEE" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."EMPLOYEE" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."EMPLOYEE" MODIFY ("EMPLOYEEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTIST
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."ARTIST" ADD CONSTRAINT "PK_ARTIST" PRIMARY KEY ("ARTISTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."ARTIST" MODIFY ("ARTISTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYLIST
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."PLAYLIST" ADD CONSTRAINT "PK_PLAYLIST" PRIMARY KEY ("PLAYLISTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."PLAYLIST" MODIFY ("PLAYLISTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICELINE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."INVOICELINE" ADD CONSTRAINT "PK_INVOICELINE" PRIMARY KEY ("INVOICELINEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("UNITPRICE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("TRACKID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("INVOICEID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICELINE" MODIFY ("INVOICELINEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "PK_TRACK" PRIMARY KEY ("TRACKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("UNITPRICE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("MILLISECONDS" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("MEDIATYPEID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."TRACK" MODIFY ("TRACKID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."INVOICE" ADD CONSTRAINT "PK_INVOICE" PRIMARY KEY ("INVOICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("INVOICEDATE" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."INVOICE" MODIFY ("INVOICEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."CUSTOMER" ADD CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."CUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDIATYPE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."MEDIATYPE" ADD CONSTRAINT "PK_MEDIATYPE" PRIMARY KEY ("MEDIATYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."MEDIATYPE" MODIFY ("MEDIATYPEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYLISTTRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" ADD CONSTRAINT "PK_PLAYLISTTRACK" PRIMARY KEY ("PLAYLISTID", "TRACKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" MODIFY ("TRACKID" NOT NULL ENABLE);
  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" MODIFY ("PLAYLISTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALBUM
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."ALBUM" ADD CONSTRAINT "FK_ALBUMARTISTID" FOREIGN KEY ("ARTISTID")
	  REFERENCES "CHINOOK"."ARTIST" ("ARTISTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."CUSTOMER" ADD CONSTRAINT "FK_CUSTOMERSUPPORTREPID" FOREIGN KEY ("SUPPORTREPID")
	  REFERENCES "CHINOOK"."EMPLOYEE" ("EMPLOYEEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."EMPLOYEE" ADD CONSTRAINT "FK_EMPLOYEEREPORTSTO" FOREIGN KEY ("REPORTSTO")
	  REFERENCES "CHINOOK"."EMPLOYEE" ("EMPLOYEEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."INVOICE" ADD CONSTRAINT "FK_INVOICECUSTOMERID" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "CHINOOK"."CUSTOMER" ("CUSTOMERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICELINE
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."INVOICELINE" ADD CONSTRAINT "FK_INVOICELINEINVOICEID" FOREIGN KEY ("INVOICEID")
	  REFERENCES "CHINOOK"."INVOICE" ("INVOICEID") ENABLE;
  ALTER TABLE "CHINOOK"."INVOICELINE" ADD CONSTRAINT "FK_INVOICELINETRACKID" FOREIGN KEY ("TRACKID")
	  REFERENCES "CHINOOK"."TRACK" ("TRACKID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAYLISTTRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" ADD CONSTRAINT "FK_PLAYLISTTRACKPLAYLISTID" FOREIGN KEY ("PLAYLISTID")
	  REFERENCES "CHINOOK"."PLAYLIST" ("PLAYLISTID") ENABLE;
  ALTER TABLE "CHINOOK"."PLAYLISTTRACK" ADD CONSTRAINT "FK_PLAYLISTTRACKTRACKID" FOREIGN KEY ("TRACKID")
	  REFERENCES "CHINOOK"."TRACK" ("TRACKID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRACK
--------------------------------------------------------

  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "FK_TRACKALBUMID" FOREIGN KEY ("ALBUMID")
	  REFERENCES "CHINOOK"."ALBUM" ("ALBUMID") ENABLE;
  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "FK_TRACKGENREID" FOREIGN KEY ("GENREID")
	  REFERENCES "CHINOOK"."GENRE" ("GENREID") ENABLE;
  ALTER TABLE "CHINOOK"."TRACK" ADD CONSTRAINT "FK_TRACKMEDIATYPEID" FOREIGN KEY ("MEDIATYPEID")
	  REFERENCES "CHINOOK"."MEDIATYPE" ("MEDIATYPEID") ENABLE;
