-- DDL for Reimbursement_db

-- Position Table
CREATE TABLE POSITION (
Pos_Id INT,
Pos_Type VARCHAR2(2000) UNIQUE NOT NULL,

PRIMARY KEY (Pos_Id)
);

-- Reimbursement Table
CREATE TABLE REIMBURSEMENT(
R_Id INT,
Amt INT NOT NULL,
Emp_U_Id INT NOT NULL,
Mgr_U_Id INT NOT NULL,
Rq_Type_Id INT,
Rq_Status_Id INT DEFAULT 1,
DESCRIPTION VARCHAR2(2000),
IMG BLOB,
TIMESUBMISSION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (R_ID),
FOREIGN KEY (Emp_U_ID) REFERENCES USERS (U_Id),
FOREIGN KEY (Mgr_U_ID) REFERENCES USERS (U_Id),
FOREIGN KEY (Rq_Type_Id)REFERENCES Rq_Type(Rq_Type_Id),
FOREIGN KEY (Rq_Status_Id)REFERENCES Rq_Status(Rq_Status_Id)
);

-- Request Status Table
CREATE TABLE RQ_STATUS (
Rq_Status_Id INT NOT NULL,
Rq_Status VARCHAR2(2000),

PRIMARY KEY (Rq_Status_Id)
);

-- Request Type Table 
CREATE TABLE RQ_TYPE (
Rq_Type_Id INT NOT NULL,
Rq_Type VARCHAR2(2000),

PRIMARY KEY (Rq_Type_Id)
);

-- Users Table
CREATE TABLE USERS (
U_Id INT,
fName VARCHAR2(4000) NOT NULL,
lName VARCHAR2(4000) NOT NULL,
Email VARCHAR2(4000) NOT NULL,
Password VARCHAR2(4000) NOT NULL,
Pos_ID INT NOT NULL,

PRIMARY KEY(U_id),
FOREIGN KEY (Pos_Id)REFERENCES POSITION(Pos_Id) 
);

-- Drop Tables
DROP TABLE POSITION;
DROP TABLE REIMBURSEMENT;
DROP TABLE RQ_STATUS;
DROP TABLE RQ_TYPE;
DROP TABLE USERS;

